### ISSUE TITLE
Doesn't build under Java 8

### ISSUE THREAD

**Issue by marshallpierce** [tbroyer/gradle-errorprone-plugin-v0.0.x#1]
Under java 8, both tests in ErrorPronePluginTest fail.

shouldSucceed is broken because the `result` local in ErrorProneCompiler is actually a `com.sun.tools.javac.main.Main$Result`, not an int, so Groovy complains:

```
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.tasks.compile.CompilationFailedException(com.sun.tools.javac.main.Main$Result)
```

shouldFail is broken because the cause of the TaskExecutionException is a similar GroovyRuntimeException.

Sorry, no PR just yet... I don't have time at the moment to figure out what's going on more specifically.

**Comment by tbroyer** [comment]
I downloaded jdk 8 today but haven't had time to investigate. Will try to find time tomorrow. Thanks for the report.

**Comment by tbroyer** [comment]
It turns out error-prone itself was not compatible with JDK8 until a couple days ago, so we'll have to wait for the next error-prone release: https://code.google.com/p/error-prone/source/detail?spec=svn8e68674a17e1d94e22a94ff46644aa39d688a7ce&r=8e68674a17e1d94e22a94ff46644aa39d688a7ce
