### ISSUE TITLE
How do I get a errorprone report?

### ISSUE THREAD

**Issue by vanniktech** [tbroyer/gradle-errorprone-plugin-v0.0.x#10]
I've tried `./gradlew clean build` but got nothing.

**Comment by tbroyer** [comment]
[Error Prone](http://errorprone.info/) does not produce reports, it fails the build and/or emits warnings during the compilation, just like the standard JavaC does.

See https://github.com/google/error-prone/tree/master/examples/gradle for a "working" example (you'd have to update the `build.gradle` though, according to the [README here](https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/README.md))

**Comment by vanniktech** [comment]
Even better. Thank you very much

**Comment by robert3005** [comment]
SGTM - sorry for not finding the issue before. It's fine with me either way you want it to be really as long as it's intentional.
