### ISSUE TITLE
Jcenter/central availability

### ISSUE THREAD

**Issue by gabrielittner** [tbroyer/gradle-errorprone-plugin-v0.0.x#11]
Can you continue publishing to jcenter/central? 0.0.7 and 0.0.7.1 aren't available there.
https://bintray.com/tbroyer/maven/net.ltgt.gradle%3Agradle-errorprone-plugin/view
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.ltgt.gradle%22%20AND%20a%3A%22gradle-errorprone-plugin%22

**Comment by tbroyer** [comment]
I switched to `plugins.gradle.org`, and they automatically redirect to JCenter when they don't host it themselves; so couldn't you just replace `jcenter()` with `maven { url "https://plugins.gradle.org/m2/" }` ?

Is there a specific reason you cannot use `plugins.gradle.org`?

**Comment by gabrielittner** [comment]
Sorry, forgot to answer.
We proxy everything through a private Nexus instance and proxying `https://plugins.gradle.org/m2/` does not seem to work. So it would be nice to still have it available in central.

**Comment by jaredsburrows** [comment]
+1 jcenter

**Comment by tbroyer** [comment]
We too do proxy `https://plugins.gradle.org/m2/` through Nexus at work, and it works like a charm.

There's apparently a caveat though: do not use the (incubating) new  `plugins {}` syntax (see https://discuss.gradle.org/t/publish-plugin-and-sonatype-ossrh/9998/16), but you're probably not using it anyway.

Closing for now; can reopen if someone comes with a compelling use case.

**Comment by chintootech** [comment]
Gradle 3.1 can't seem to find 0.0.8, 

```
  > Could not resolve net.ltgt.gradle:gradle-errorprone-plugin:0.0.8.
     > Could not get resource 'https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/0.0.8/gradle-errorprone-plugin-0.0.8.pom'.
        > Could not HEAD 'https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/0.0.8/gradle-errorprone-plugin-0.0.8.pom'.
           > org.apache.http.client.ClientProtocolException (no error message)
  > Could not resolve net.ltgt.gradle:gradle-errorprone-plugin:0.0.8.
     > Could not get resource 'https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/0.0.8/gradle-errorprone-plugin-0.0.8.pom'.
        > Could not HEAD 'https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/0.0.8/gradle-errorprone-plugin-0.0.8.pom'.
           > org.apache.http.client.ClientProtocolException (no error message)
```

**Comment by jaredsburrows** [comment]
@chintootech This must be on your end. I have many github projects that use this plugin just fine.

**Comment by tbroyer** [comment]
Assuming https://github.com/alapshin/android-boilerplate or similar here, the culprit indeed is Kapt. See https://github.com/gradle/gradle/issues/6573

I'd suggest you keep using 0.0.16 until either Gradle 5, or Kapt is changed to no longer pass `-proc:none`.

As a workaround, you could possibly try to reconfigure the `JavaCompile` tasks to no longer pass `-proc:none`, and possibly reconfigure their `options.annotationProcessorPath` to include only Error Prone (e.g. setting it to `configurations.errorprone`).

Some additional notes below:

> > You could run with --debug and look for Java compiler arguments: line
> 
> I tried `./gradlew --debug compileDebugSources > log.txt` but there is no such line in the log. No `-processorpath` either.

Ah yes, the line is `Compiler arguments:` and contains `-proc:none`.

> This didn't work however `./gradlew app:dependencies --configuration debugAnnotationProcessor` did. Output:

    debugAnnotationProcessor - Classpath for the annotation processor for 'debug'. (n)
    No dependencies

The configuration we're looking for is actually `debugAnnotationProcessorClasspath`, and correctly contains Error Prone.
