### ISSUE TITLE
Adding the gradle-errorprone-plugin causes "bad path element" warnings, need to add "-Xlint:-path" to compilerArgs

### ISSUE THREAD

**Issue by Flowdalic** [tbroyer/gradle-errorprone-plugin-v0.0.x#15]
After adding the plugin, I got "bad path element" warnings (similar to [GRADLE-6 of Spring Framework](https://jira.spring.io/browse/GRADLE-6)). The warnings look like

```
warning: [path] bad path element "/home/flo/data/code/foo/foo-integration-test/build/resources/main": no such file or directory
error: warnings found and -Werror specified
1 error
1 warning
```

Where the foo-integration-test subproject has no `src/main/resources` directory or the directory is empty.

I worked around by adding

``` groovy
tasks.withType(JavaCompile) {
    options.compilerArgs = [
            '-Xlint:-path',
        ]
}
```

to my `build.gradle`.
I'm not sure, but I would guess that gradle usually does add "-Xlint:-path' automatically for every build, and adding gradle-errorprone-plugin prevents that somehow.

**Comment by tbroyer** [comment]
Gradle does not add `Xlint:-path` (a `git grep` reveals that it only uses `Xlint` in its own build scripts or in Java compiler tests.
And the gradle-errorprone-plugin uses the same `JavaCompilerArgumentsBuilder` from Gradle to generate the compiler arguments.
**But** Error Prone embeds its own `javac` (a snapshot of OpenJDK 9: https://github.com/google/error-prone-javac) so it might be a difference in there, or maybe in the way the Java compiler is invoked.

Could you run Gradle with `--debug` and diff the `Compiler arguments:` line with and without the plugin?

(BTW, I don't have `build/resources/main` in the classpath in my builds)

**Comment by tbroyer** [comment]
This issue has been inactive for a long time. Closing.

**Comment by tbroyer** [comment]
Turns out it's a JavaC bug, see #31
