### ISSUE TITLE
Option to mark warnings as errors

### ISSUE THREAD

**Issue by vanniktech** [tbroyer/gradle-errorprone-plugin-v0.0.x#24]
I don't know if this is the right place to post this but I'd love an option to mark warnings as errors so that even warnings won't get ignored.

**Comment by tbroyer** [comment]
In any Gradle project (with or without Error Prone):

``` gradle
tasks.withType(JavaCompile) {
  options.compilerArgs += [ '-Werror' ]
}
```

or if you want it selectively for specific checks: http://errorprone.info/docs/flags

**Comment by vanniktech** [comment]
Thanks for the quick reply. Is there any way to specify that only error prone warnings should be raised to errors?

**Comment by tbroyer** [comment]
I don't think this is possible; you'd have to list each check to bump its severity.

Feel free to ask at https://groups.google.com/d/forum/error-prone-discuss or file an issue at https://github.com/google/error-prone, but in any case this is independent from this plugin.
