### ISSUE TITLE
Plugin stopped working on Windows 10

### ISSUE THREAD

**Issue by koppor** [tbroyer/gradle-errorprone-plugin-v0.0.x#25]
At several machines on Windows 10, the plugin fails:

```
:compileJavaC:\git-repositories\jabref\jabref\src\main\java\net\sf\jabref\BibDatabaseContext.java:1: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
package net.sf.jabref;
^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.10
     Stack Trace:


```

Steps to reproduce (on Windows! - on linux, everything is allright)
1. Download https://github.com/JabRef/jabref/archive/v3.5.zip
2. Execute `gradlew run`

```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Microsoft Windows [Version 10.0.10586]
```

**Comment by tbroyer** [comment]
This is google/error-prone#432 (see also google/error-prone#437)

**Comment by koppor** [comment]
Thank you for the quick pointer! The issue was that the exception is not shown at all and thus makes it hard to do a good report.

**Comment by tbroyer** [comment]
Yes, I understand that, and looked at it before closing this issue; but that would be a bug in ErrorProne too (or Guava, or actually more likely the JVM itself‽), as the stacktrace is passed as a string to the error message: https://github.com/google/error-prone/blob/2b610a6204da9281b5382b55a6d03109fd5001e5/core/src/main/java/com/google/errorprone/ErrorProneError.java#L57 (see https://github.com/google/error-prone/blob/2b610a6204da9281b5382b55a6d03109fd5001e5/core/src/main/java/com/google/errorprone/errors.properties#L20 for the error message), and that string is obtained by rather straightforward code that hasn't changed for years: https://github.com/google/guava/blame/d6ef78ff26c28401c4bd8a61b75cfdf052b65696/guava/src/com/google/common/base/Throwables.java#L294-L298
