### ISSUE TITLE
how to configure check severity?

### ISSUE THREAD

**Issue by phraktle** [tbroyer/gradle-errorprone-plugin-v0.0.x#29]
Hi,

http://errorprone.info/docs/flags lists how one can configure severity of specific checks via command line arguments. How do you configure the same with the gradle plugin?

Thanks,
  Viktor

**Comment by tbroyer** [comment]
Like any other compiler argument:

``` gradle
tasks.withType(JavaCompile) {
  options.compilerArgs += [ '-Xep:DeadException:WARN', '-Xep:GuardedByValidator:OFF' ]
}
```

Should we add a Gradle subsection on the Error Prone documentation page? and/or add the above on the README here?

**Comment by phraktle** [comment]
Hi @tbroyer,

Thanks, that works! Having it in the gradle plugin README would indeed be helpful (I looked there first :)

Regards,
  Viktor

**Comment by tbroyer** [comment]
Done: 1e062cbffc4bcb43f43287c7896c5ea98619d7db
