### ISSUE TITLE
[Request] HTML reports of errorprone

### ISSUE THREAD

**Issue by jaredsburrows** [tbroyer/gradle-errorprone-plugin-v0.0.x#32]
Instead of looking at the console log output, could we create an HTML report of the issues found by errorprone?

**Comment by stkent** [comment]
+1 for this and XML output to allow automated parsing of the results!

**Comment by tbroyer** [comment]
This is a request to be made to the Error Prone project itself; or to Gradle itself (there's no reason to make it specific to Error Prone after all; a standard JavaC build could have many warnings and errors too).

I'm not going to add anything specific to this plugin I'm afraid (unless maybe there's some agreement on the Gradle side, to make it available in earlier versions of Gradle before the change lands in a new Gradle release).

**Comment by jaredsburrows** [comment]
@tbroyer Are you wanting to close this? I just wanted an HTML report of errorprone specific issues. Say if I have a project that already is using `-Werror` and have all the `javac` warnings done, it would be nice to have a list of errors from just errorprone.

**Comment by jaredsburrows** [comment]
Im closing this as we do not want to parse error-prone output.
