### ISSUE TITLE
Use a fixed version of errorprone

### ISSUE THREAD

**Issue by markelliot** [tbroyer/gradle-errorprone-plugin-v0.0.x#35]
Are you open to using a fixed version of errorprone in this plugin, rather than latest.release?

We'd like to use this plugin but generally want our builds to be stable/reproducible, unfortunately, pulling latest means that a build that works today may not be capable of rebuilding in the future.

**Comment by tbroyer** [comment]
Doesn't the README explain how to do this? (and yes, I agree you should use a fixed version!)

**Comment by markelliot** [comment]
Yep, sorry, I'll just add an entry to nebula and call it a day -- was sort of hoping the default behavior would be safer, that's all.

**Comment by tbroyer** [comment]
Well, if the default was a fixed version, I'd either have to cut new releases every time there's a new errorprone, or many will just continue to use an old version (bad default). An alternative would be to not have defaults at all, but that's burdensome. I think latest.release actually is the safest default / best compromise: forces a recent errorprone (at the expense of reproducibility), but you can get reproducibility easily by declaring a fixed version (or even a forked version, or some other resolution rule)
