### ISSUE TITLE
why

### ISSUE THREAD

**Issue by youcan10** [tbroyer/gradle-errorprone-plugin-v0.0.x#40]
[root@localhost azkaban]# ./gradlew distTar
Parallel execution with configuration on demand is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_bt4hi2fdrezlg33zs9uy3axix.run(/usr/local/src/azkaban/build.gradle:14)
:azkaban-spi:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':azkaban-spi:compileJava'.
> Could not initialize class net.ltgt.gradle.errorprone.ErrorProneCompiler$SelfFirstClassLoader

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tbroyer** [comment]
Could be #27 or #34. Please provide more information (I see that https://github.com/azkaban/azkaban uses version 0.0.8 of the plugin; a message to help detect #34 has been added to 0.0.9, so maybe first try using 0.0.9, or 0.0.10)
