### ISSUE TITLE
[Feature Request] - Support Groovy

### ISSUE THREAD

**Issue by jaredsburrows** [tbroyer/gradle-errorprone-plugin-v0.0.x#41]
Can we add support for Gradle's `GroovyCompile` task by adding that code here: https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/src/main/java/net/ltgt/gradle/errorprone/ErrorPronePlugin.java#L16?

**Comment by jbduncan** [comment]
I believe that error-prone doesn't support compilation of Groovy sources. Or have I misunderstood what you're requesting, @jaredsburrows?

**Comment by jaredsburrows** [comment]
@jbduncan Alright. I have added asked for this feature in error-prone's repository here: https://github.com/google/error-prone/issues/623.
