### ISSUE TITLE
Is errorprone-base plugin published?

### ISSUE THREAD

**Issue by bjkeller** [tbroyer/gradle-errorprone-plugin-v0.0.x#44]
I need to exclude a source set in a project -- it contains intentionally buggy code.  

When I attempt to use the plugins line:
```
id "net.ltgt.errorprone-base" version "0.0.10"
```
the plugin is not found. 

Have I missed a detail?

**Comment by tbroyer** [comment]
Ha, good catch! It actually was never published to the Plugins Portal so it cannot be used with the plugins DSL. You can use it with `apply plugin:` though.

**Comment by tbroyer** [comment]
Just released v0.0.11, which now publishes `net.ltgt.errorprone-base` to the Gradle Plugin portal so you can use the `plugins` DSL: https://plugins.gradle.org/plugin/net.ltgt.errorprone-base
