### ISSUE TITLE
How to use it with checker-framework?

### ISSUE THREAD

**Issue by m-titov** [tbroyer/gradle-errorprone-plugin-v0.0.x#47]
https://github.com/jaredsburrows/gradle-checker-framework-plugin

**Comment by tbroyer** [comment]
According to https://checkerframework.org/manual/#gradle, it's not necessary to fork the compiler when using Java 8, which ErrorProne requires anyway.

The gradle-checker-framework-plugin apparently unconditionally forks; if manual configuration works, then you should probably file a bug against the plugin such that it doesn't fork when not needed.

(also note that the checker framework documentation and the gradle-checker-framework-plugin won't work if you have annotation processors, as they configure an explicit `-processor` and `-processorpath`; and also note that they both overwrite the `compilerArgs`, in case you'd like to configure any, such as `-Xlint` and/or `-Werror`)
