### ISSUE TITLE
How to exclude files from error-prone ?

### ISSUE THREAD

**Issue by stephanenicolas** [tbroyer/gradle-errorprone-plugin-v0.0.x#51]
Hi, 

is there any way to get error prone not analyzing (or reporting at least) files based on a regex ? 
Error prone finds some errors in generated code that we would like to discard.

Thx

**Comment by tbroyer** [comment]
Duplicate of #36 and #42 

This plugin is _only_ about enabling Error Prone; all configuration goes through compile options' `compilerArgs`, following [what's possible at Error Prone's level](http://errorprone.info/docs/flags); specifically, in this case, `-XepDisableWarningsInGeneratedCode` (only warnings though, not errors).

Issues linked above in turn link to Error Prone issues about similar feature requests.
