### ISSUE TITLE
Use com.google.errorprone.ErrorProneJavaCompiler for full Java 9 language support?

### ISSUE THREAD

**Issue by cushon** [tbroyer/gradle-errorprone-plugin-v0.0.x#52]
Have you considered having `gradle-errorprone-plugin` use `com.google.errorprone.ErrorProneJavaCompiler` instead of `com.google.errorprone.ErrorProneCompiler`? The latter tries to wrap the javac CLI, and is going to need significant updates to support the Java 9 language level. `ErrorProneJavaCompiler` is a `javax.tools.JavaCompiler` implementation that gets most of its Java 9 support for free. I'm wondering if we can get Java 9 language support in Error Prone by migrating to `ErrorProneJavaCompiler`, instead of updating `ErrorProneCompiler`.

Would `org.gradle.api.internal.tasks.compile.JdkJavaCompiler` and `ErrorProneJavaCompiler` be a viable replacement for `net.ltgt.gradle.errorprone.ErrorProneCompiler`?

**Comment by tbroyer** [comment]
Now that I only support Error Prone 2.x, using `ErrorProneJavaCompiler` is an option yes.

I have doubts about how to make it work with `JdkJavaCompiler` though: we'd need to expose `ErrorProneJavaCompiler` as a `javax.tools.JavaCompiler` to Gradle's `JdkJavaCompiler`, but that means using the current JVM's `JavaCompiler` (and referenced classes), not the one(s) from `com.google.errorprone:javac'. This might work for Java 9, but probably not with Java 8. Were you thinking about only doing this when the current JVM is Java 9?

Btw, see also https://github.com/gradle/gradle/issues/1652 regarding toolchain/compiler selection in Gradle.

**Comment by cushon** [comment]
You're right - using an isolated classloader is still a good idea, even if we only cared about JDK 9 support. The `javax.*` APIs we depend on will likely continue to change.

I think that `ErrorProneJavaCompiler` is still a good way to get Java 9 support, even if `JdkJavaCompiler` can't be used and some of that set-up logic has to be duplicated. If you see any issues or missing features with `ErrorProneJavaCompiler` that are blockers for that, please let me know.

**Comment by tbroyer** [comment]
Fwiw, I managed to get things working without any duplication (by loading `JdkJavaCompiler` and a couple other classes **into** the errorprone classloader –getting their bytes through `getResourceAsStream` and calling `defineClass()`–, changing the errorprone classloader's parent to be the Gradle/plugin class loader).
I had tried many things, so need to clean the code before pushing.

Unfortunately, I had a slight hope that the `--release` option would be supported, but it still gives me `release version 8 not supported`.

**Comment by cushon** [comment]
Thanks for looking in to this! Does `--release` work using a stock `JdkJavaCompiler` without Error Prone? I'm wondering if this is an issue with Error Prone / the repackaged javac, or with gradle.

**Comment by tbroyer** [comment]
`--release` works fine with Gradle (without Error Prone). But I wonder, doesn't JavaC needs to load the definitions for the releases from somewhere? (presumably somewhere in the java.home) Could that be the issue? (note that I tested `--release` with a JDK 9, so Error Prone could have found it, except maybe the way it's loaded it doesn't know where to look at? or doesn't "see" them for some reason?)

**Comment by cushon** [comment]
error-prone-javac is missing `classes/META-INF/services/com.sun.tools.javac.platform.PlatformProvider`, which is what discovers the information needed for `--release` in the current JDK.

If you want to run another experiment, you could try using Error Prone on JDK 9 without any of the isolated class-loading, so it gets the javac from the host JDK 9. If that works, it would confirm my theory.

**Comment by tbroyer** [comment]
So, I ran a few experiments. `getResources` is indeed called with `META-INF/services/com.sun.tools.javac.platform.PlatformProvider` as argument, but finds nothing (note that the classloader is no longer "isolated", it delegates to the "current" classloader as I now rely on Gradle classes); I suppose this might have something to do with JPMS encapsulation…

I copied `META-INF/services/com.sun.tools.javac.platform.PlatformProvider` to the plugin source tree and made sure the classloader would find it, and then my test using `--release` passes!

Having error-prone-javac ship with the `META-INF/services/com.sun.tools.javac.platform.PlatformProvider` would fix this then (would be great to have it in 2.1.3 ;-) )

**Comment by cushon** [comment]
Thanks! I filed https://github.com/google/error-prone/issues/784 for the `error-prone-javac` fix.

**Comment by cushon** [comment]
The next release of Error Prone will include a fix for google/error-prone#784.

**Comment by cushon** [comment]
I pushed a 2.2.0 release that includes the fix.

**Comment by tbroyer** [comment]
Thanks, now testing the `--release` flag in 530fae4, and updated the build to use it in dd858a4. For now, using `ErrorProneJavaCompiler` instead of `ErrorProneCompiler` is still in a branch (so leaving this issue open)

**Comment by tbroyer** [comment]
Plugin is moving to using `-Xplugin:ErrorProne`; see https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin.
