### ISSUE TITLE
Allow a DiagnosticListener to be passed through to ErrorProne

### ISSUE THREAD

**Issue by felixdesouza** [tbroyer/gradle-errorprone-plugin-v0.0.x#54]
I'm able to capture the standard output by hooking into the logger, however I want a structured format so I could use it [here](https://github.com/palantir/gradle-circle-style/). Steps would be either to parse the standard err for any error prone errors. However it's somewhat freeform and I was wondering whether we could do any better with considerably less effort/less "error prone" approach (sorry had to).

`DiagnosticListener.report()` is called whenever an event during compilation occurs. Digging through the code for here and errorprone, there appears to be a method on (in errorprone) `ErrorProneCompiler.Builder.listenToDiagnostics()`.

Are there any caveats to adding an extension (I think that's what it's called) that allowed me to pass in a diagnostic listener. e.g.:

```java
errorprone {
    diagnosticListener structuredDiagnosticListener()
}
```

I'm not sure how much it would interfere with #52, but I seem to be able to see `DiagnosticListener` sprinkled around `ErrorProneJavaCompiler` too.

Thoughts?

**Comment by tbroyer** [comment]
What about other compilation warnings and errors from javac? (for those who don't use errorprone) That looks like something that would better be added at Gradle's level.

**Comment by felixdesouza** [comment]
This is true and a fair point, this was the first place I thought of (did some further digging inside gradle in addition to here and errorprone). 

What would that mean for libraries like yours? Wouldn't that place a dependency on a fairly high version of gradle? Considering you currently support gradle versions 2.6 - 4.3. Not hugely familiar with writing Gradle plugins so this could be a non-issue 🤷‍♂️ 

It's not a reason *for* doing so, I'm just curious as to what would happen should it be the case.

**Comment by felixdesouza** [comment]
Actually I think I'll backtrack. It makes less sense for general compilation as you'd get that feedback from your IDE and not have to wait for CI to tell you that you can't compile code. Whereas the errors/warnings you'd get here would be similar to pushing code and not running "Findbugs" etc.

Most team members may optionally choose to run errorprone as their compiler in their IDE or maybe they won't have that option (read: eclipse users - from what I saw on error prone's site). Meaning they'd get these errors at CI time if they don't run `compileTestJava` locally, but the problem then becomes parsing the output can be quite annoying. Even if they run `compileTestJava` locally.

Perhaps instead of allowing a general diagnostic listener, we could instead just generate a JUnit report?

I'm happy to put something up if you agree with the above premise.

**Comment by tbroyer** [comment]
Plugin is moving to passing `-Xplugin:ErrorProne` compiler argument to a standard `JavaCompile` (see https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin), so this would have to be done at Gradle level (or possibly another plugin that would intercept the task output and parse it, or do its own `JavaToolchain` thing).
