### ISSUE TITLE
Compile fails if there is no internet access

### ISSUE THREAD

**Issue by magneticflux-** [tbroyer/gradle-errorprone-plugin-v0.0.x#57]
I get a `ConnectException` with the message `Connection timed out: connect` when I try to build. The error is thrown when trying to resolve `com.google.errorprone:error_prone_core:latest.release`. I have a version of errorprone in my Gradle cache that I would expect it to fall back to.

**Comment by tbroyer** [comment]
This is using standard Gradle dependency resolution. What happens here is that `latest.release` (aka dynamic) versions are checked every 24h.
You can easily tell Gradle to not try to reach the network by using `--offline`: https://docs.gradle.org/current/userguide/dependency_management.html#sec:cache_command_line_options
You can also, and I would recommend that if you're ready to check for new versions on a regular basis, use a fixed version (see README for the instructions)
