### ISSUE TITLE
Register error prone as a compiler plugin

### ISSUE THREAD

**Issue by oehme** [tbroyer/gradle-errorprone-plugin-v0.0.x#63]
Now that Gradle has a standardized way to add dependencies to the annotation processor path, this plugin should make use of that and register error prone as a compiler plugin instead of implementing a custom tool chain.

This would remove loads of internal API usage and potential for breakage going forward.

**Comment by tbroyer** [comment]
See https://twitter.com/tbroyer/status/973950255375974402

 * only works with Gradle 4.6+ (this plugin supports Gradle versions back to 2.6)
 * only works with Java 9+ (Java 8 is LTS, I use Java 8 as my main JDK; I'll wait for Java 11 to really make the switch)
 * breaks as soon as someone reassigns `options.annotationProcessorPath`
 * breaks everyone currently relying on annotation processors from the compile classpath (Gradle 4.6+ warns, and Gradle 5.0 will disable it, but see above about the Gradle versions currently supported by this plugin)
 * "leaks" Error Prone dependencies into the annotation processor path, and more importantly affects Gradle dependency resolution/conflict.
 * requires `--add-exports` and `--add-opens`, so probably requires forking?

Overall, I think it is actually a **bad** idea.

For people who'd want to do this, it should be just a few lines of code (totally untested):
```gradle
sourceSets.all {
  dependencies.add(it.annotationProcessorConfigurationName, "com.google.errorprone:error_prone_core:2.2.0")
  tasks[it.compileJavaTaskName].configure {
    options.compilerArgs << '-Xplugin:ErrorProne'
    fork = true
    forkOptions.jvmArgs += [
      '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED',
      '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED',
      '--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED'
    ]
}
```

**Comment by oehme** [comment]
How about having another plugin then which is targeted at Gradle 4.6+ users who also have their annotation processors properly configured (which is necessary to work in 5.0)?

> only works with Java 9+ (Java 8 is LTS, I use Java 8 as my main JDK; I'll wait for Java 11 to really make the switch)

Why? Afaik `-Xplugin` has been around since Java 8.

> breaks as soon as someone reassigns options.annotationProcessorPath

Sure, but that's true for overwriting any task property, so not really an issue in my eyes.

> "leaks" Error Prone dependencies into the annotation processor path, and more importantly affects Gradle dependency resolution/conflict.

How is that different from annotation processors having conflicting dependencies?

> requires --add-exports and --add-opens, so probably requires forking?

Forking is better anyway to reduce GC pressure on the main daemon. But it would work without too if you add the exports to the main daemon vm args. The plugin could either default to forking or tell the user that they have to add those exports if they don't want to fork.

Overall I think this would make for a much simpler plugin that is way less likely to break. Also I got an error report from @liutikas, which pointed at [this line](https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java#L63) failing occasionally. With the compiler plugin approach there would be one less point of failure.

That's my Spiel :) Thanks for writing up the sample code above. If you don't decide to go for this feature, at least users will have some alternative or someone else can write such a plugin.

**Comment by tbroyer** [comment]
> How about having another plugin then

Why not indeed :wink: 

> Afaik `-Xplugin` has been around since Java 8.

The steps for Java 8 at http://errorprone.info/docs/installation#command-line don't use it at least. I suspect there are conflicts between the `com.sun.tools.javac` APIs that ErrorProne uses (based on Java 9, provided by com.google.errorprone:javac, which would probably need to be added to the bootstrap classpath BTW on Java 8), and the ones from the JDK.

And it indeed doesn't work with OpenJDK 8:
```
$ javac -Xbootclasspath/p:error_prone_ant-2.2.0.jar  -processorpath error_prone_ant-2.2.0.jar -Xplugin:ErrorProne Foo.java


A plugin threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:189)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:38)
	at com.sun.tools.javac.main.Main.compile(Main.java:470)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)
```
(I tried with and without the `-Xbootclasspath/p:`)

Also, `-Xplugin` might not be supported by other JDKs than OpenJDK/Oracle (no idea if that's an actual issue; but from my tests this plugin currently works –I just re-tested– with an IBM JDK: https://github.com/gradle/gradle/issues/1645#issuecomment-290026173; admittedly, IBM JDK likely is based)

> How is that different from annotation processors having conflicting dependencies?

It's not; it just adds to the probabilities of conflicts; which is also one reason annotation processors tend to "shade" their dependencies (ErrorProne does not).

> Thanks for writing up the sample code above. If you don't decide to go for this feature, at least users will have some alternative

Yes, that's why I took the time to write it down; as @JakeWharton (also an Android engineer at Google :wink:) actually asked me the same on Twitter a few hours before you opened that issue: https://twitter.com/JakeWharton/status/973938262174814208

I'll keep this issue open for a bit (let me see if I actually want to build that other plugin :wink:) and close when I take my decision.

**Comment by tbroyer** [comment]
Spent a few hours today building https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin

Note that one big difference between both approaches is that by using `-Xplugin` ErrorProne flags need to be passed within the `-Xplugin` argument, and cannot simply be passed to `options.compilerArgs`, requiring a DSL extension. This also means that those arguments cannot contain spaces, as JavaC will parse them by simply splitting on whitespace: https://github.com/google/error-prone-javac/blob/b9027b15d82cc3d9d16981a9f6ffd4f0801aa482/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Arguments.java#L809-L819

I still believe that Gradle should somehow have an API allowing users to plug any `javax.tool.JavaCompiler`, with a custom classpath/classloader/bootstrap-classpath.

**Comment by oehme** [comment]
Well the problem with hooking in other compilers is that you loose everything we build into ours, e.g. incremental annotation processing. That's why I'm generally in favor of plugins for things that are just valitating/decorating.

**Comment by oehme** [comment]
Thanks for building that plugin!
