### ISSUE TITLE
Support for Refaster

### ISSUE THREAD

**Issue by jbduncan** [tbroyer/gradle-errorprone-plugin-v0.0.x#65]
Recently, I've been looking into getting [Refaster](http://errorprone.info/docs/refaster), part of error-prone, set up for a currently private Gradle project, but I've not been able to find any docs or code references to Refaster in gradle-errorprone-plugin, so I've been trying to hack together a solution with limited success so far...

If there is support in gradle-errorprone-plugin for Refaster, then I'd be very grateful for some pointers! But if there's no support, would it be considered as a possible new feature?

**Comment by tbroyer** [comment]
There's currently no support for Refaster, but yes this is something I've been thinking about.

More accurately, I've been thinking about "patching" (for regular bug checks), but would need guidance from Gradle devs to get the design right.

**Comment by jbduncan** [comment]
Sounds good to me!

If you do manage to get something working in the future, then great! But if not, then that's fine too; I do not want to put you under any pressure. :)

**Comment by jbduncan** [comment]
I recently open sourced the project I mentioned above (licensed Apache 2.0), where I made efforts to turn Refaster into a Gradle buildSrc plugin. I'm sharing a link to the plugin with you in the hope that it helps. https://github.com/jbduncan/jupiter-collection-testers/tree/master/buildSrc

**Comment by tbroyer** [comment]
I'm deprecating this plugin in favor of https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin (repos and plugins will soon be renamed so the new one replaces this one).
I also think it would work better as a separate plugin (patching could be part of the ErrorProne plugin, probably not compilation of refaster templates though), so I'm closing the issue here and not port it over to the new project.

**Comment by jbduncan** [comment]
> I also think it would work better as a separate plugin (patching could be part of the ErrorProne plugin, probably not compilation of refaster templates though), so I'm closing the issue here and not port it over to the new project.

Oh okay. Kind of sad to hear, but cheers for considering this issue though! I'll continue working on my `buildSrc`-based plugin, and if I grow confident I may decide to split it out into its own open source project. So stay tuned if this is of interest to you. :)
