### ISSUE TITLE
Should gradle-errorprone-plugin use latest.release as DEFAULT_DEPENDENCY in ErrorProneBasePlugin.java

### ISSUE THREAD

**Issue by penkzhou** [tbroyer/gradle-errorprone-plugin-v0.0.x#71]
I use gradle-errorprone-plugin in my project and it works in most cases. 
But sometimes the build will failed because the gradle-errorprone-plugin use the latest release and it will break the build unexpected. Wish it will be a stable release version.

**Comment by tbroyer** [comment]
This is why the README documents how to use a fixed version.

I don't want to set a fixed version in the plugin itself, so there are only two choices (that I can think of):
 * use `latest.release`; it might break some projects when a new version of Error Prone is released, and then people (hopefully) learn to pin the version;
 * error out and force users to configure the dependency.

AFAIR, when I started writing the plugin, the latter wasn't possible, so I went with the former. I wouldn't mind changing though. WDYT? Would you have preferred a developer experience where the doc says "you need to configure a dependency" and having an error message if you didn't?

Note: I could also keep the current behavior and add a warning in the README that not pinning a version will lead to builds breaking without notice.

**Comment by penkzhou** [comment]
Thanks for the detail response. I understand your choice and I will configure the specific  Error Prone version in the gradle script. 
In addition, adding a warning in the README will be better.

**Comment by tbroyer** [comment]
Fwiw, warning added to the plugin in 92d1b429e6148d3b2ef0b5cfa0a63c78be227301 (in case you don't configure Error Prone dependencies explicitly, whether you use a dynamic or changing version or not), and to the README in 29008711c10045ec4e3dc336faec3e1429e0010b (about the use of changing or dynamic versions)
