### ISSUE TITLE
Use Task Configuration Avoidance?

### ISSUE THREAD

**Issue by jbduncan** [tbroyer/gradle-errorprone-plugin-v0.0.x#73]
gradle-errorprone-plugin's "net.ltgt.errorprone" sub-plugin currently configures all `JavaCompile` tasks [eagerly](https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/src/main/java/net/ltgt/gradle/errorprone/ErrorPronePlugin.java#L24-L28), whereas I suspect this can be done lazily via [Task Configuration Avoidance](https://docs.gradle.org/4.9/userguide/task_configuration_avoidance.html) as of Gradle 4.9.

I'm reporting this because I'm in the middle of migrating my custom Refaster plugin to use Task Configuration Avoidance in branch https://github.com/jbduncan/jupiter-collection-testers/tree/migrate-task-configuration-avoidance, but when I try to use gradle-errorprone-plugin together with my plugin, the `JavaCompile` tasks that my plugin lazily registers get eagerly created anyway. I suspect that this is because:

1. gradle-errorprone-plugin eagerly configures _all_ `JavaCompile` tasks to use the error-prone compiler.
2. My own plugin only activates when ["net.ltgt.errorprone" is applied](https://github.com/jbduncan/jupiter-collection-testers/blob/master/buildSrc/src/main/java/com/github/jbduncan/gradle/refaster/RefasterPlugin.java#L43-L45) (rather than "net.ltgt.errorprone-base").

**Comment by tbroyer** [comment]
Just released v0.0.16 with this change

**Comment by jbduncan** [comment]
Wow, great! Thank you for such a quick response. I'll give v0.0.16 a go hopefully sooner rather than later. :)
