### ISSUE TITLE
Wrong description on plugin central

### ISSUE THREAD

**Issue by Vampire** [tbroyer/gradle-errorprone-plugin-v0.0.x#9]
https://plugins.gradle.org/plugin/net.ltgt.errorprone has as description "Gradle plugin making it easier/safer to use Java annotation processors" which was probably a copy&paste error.

**Comment by tbroyer** [comment]
It was, but I fixed it since then :-/
(in 9e7d116d2c4137b2b4b45e94afc63e90f8e7ecb0; compare https://plugins.gradle.org/plugin/net.ltgt.errorprone/0.0.7 with https://plugins.gradle.org/plugin/net.ltgt.errorprone/0.0.7.1)

I'll ping Gradleware about it, thanks

**Comment by tbroyer** [comment]
Was fixed some time ago already actually: https://discuss.gradle.org/t/plugin-pending-approval-for-one-week/9588/4
